assets:
  backgrounds:
    mountain_rain: /assets/bg/mountain_rain.png
    rain_corridor: /assets/bg/rain_corridor.png
    ryokan_hall: /assets/bg/ryokan_hall.png
    tea_room: /assets/bg/tea_room.png
    case_board: /assets/bg/case_board.png
    police_tape: /assets/bg/police_tape.svg
    clue_cup: /assets/bg/clue_cup.svg
    clue_lid: /assets/bg/clue_lid.svg
  characters:
    코난:
      base: /assets/char/conan/base.png
      emotions:
        think: /assets/char/conan/think.png
        serious: /assets/char/conan/serious.png
    란:
      base: /assets/char/ran/base.png
      emotions:
        surprised: /assets/char/ran/surprised.png
        worried: /assets/char/ran/worried.png
    코고로:
      base: /assets/char/kogoro/base.png
      emotions:
        proud: /assets/char/kogoro/proud.png
        angry: /assets/char/kogoro/angry.png
    켄지:
      base: /assets/char/kenji/base.png
      emotions:
        angry: /assets/char/kenji/angry.png
    신이치:
      base: /assets/char/shinichi/base.png
      emotions:
        cold: /assets/char/shinichi/cold.png
    레이코:
      base: /assets/char/reiko/base.png
      emotions:
        nervous: /assets/char/reiko/nervous.png
    하루오:
      base: /assets/char/haruo/base.png
      emotions:
        scared: /assets/char/haruo/scared.png
  music:
    reasoning: /assets/music/reasoning.mp3
    confession: /assets/music/confession.mp3
    solvethecase: /assets/music/solvethecase.mp3
  sfx:
    thunder: /assets/sfx/thunder.wav
    scream: /assets/sfx/scream.wav
    door: /assets/sfx/door.wav
    cup_clink: /assets/sfx/cup_clink.wav
    notebook_flip: /assets/sfx/notebook_flip.wav
state:
  investigation_count: 0
  visited_shinichi: false
  visited_reiko: false
  visited_kenji: false
  visited_haruo: false
  deduction_score: 0
  final_confidence: 0
  trust: 0
  mistake_count: 0
  comeback_chance: 1
  early_exit_taken: false
  clue_rim_reagent: false
  clue_order_note: false
  clue_double_press_decoy: false
  clue_haruo_wipe: false
  reiko_motive_open: false
  timeline_answer: ""
  culprit_answer: ""
